apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devconf-us-2021-mimotej
spec:
  project: workshops
  source:
    path: manifests/overlays/test
    repoURL: "https://github.com/mimotej/elyra-aidevsecops-tutorial.git"
    targetRevision: HEAD
    kustomize:
      namePrefix: mimotej-
  destination:
    namespace: elyra-aidevsecops-tutorial
    name: devconfus2021
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
