---
exclude: .github/workflows
repos:
  - repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: remove-tabs
        exclude: \.rego$

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-symlinks
      - id: detect-private-key

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.2
    hooks:
      - id: yamllint
        files: \.ya?ml$
        types: [file, yaml]
        entry: 'yamllint --strict -d "{ignore: kustomization.yaml}"'

  - repo: https://github.com/anderseknert/pre-commit-opa
    rev: v1.4.1
    hooks:
      - id: opa-fmt
      - id: conftest-test
        files: \.ya?ml$
        exclude: ^\..*
        types: [file, yaml]
      - id: conftest-verify
        files: \.ya?ml$
        exclude: ^\..*
        types: [file, yaml]
