presubmits:
  - name: kustomize-build
    decorate: true
    max_concurrency: 1
    run_if_changed: ".*yaml"
    skip_report: false
    context: aicoe-ci/prow/kustomize-build
    spec:
      containers:
        - image: quay.io/operate-first/opf-toolbox:latest
          command:
            - "test-kustomize-build"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
  # - name: conftest
  #   decorate: true
  #   max_concurrency: 1
  #   run_if_changed: ".*yaml"
  #   skip_report: false
  #   context: aicoe-ci/prow/conftest
  #   spec:
  #     containers:
  #       - image: quay.io/operate-first/opf-toolbox:v0.3.2
  #         command:
  #           - "test-conftest"
  #         resources:
  #           requests:
  #             memory: "256Mi"
  #             cpu: "200m"
  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/pre-commit
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-precommit-py38:v0.12.5
          command:
            - "pre-commit"
            - "run"
            - "--all-files"
          resources:
            requests:
              memory: "2Gi"
              cpu: "200m"
