apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: devconf-us-2021
spec:
    generators:
        - list:
              elements:
                  - user: tumido
    template:
        metadata:
            name: "elyra-aidevsecops-tutorial-{{user}}"
        spec:
            project: workshops
            source:
                path: manifests/overlays/test
                repoURL: "https://github.com/{{user}}/elyra-aidevsecops-tutorial.git"
            destination:
                name: zero
                namespace: "devconf-us-2021-{{user}}"
            syncPolicy:
                automated:
                    selfHeal: true
                    prune: true
                syncOptions:
                    - Validate=false
