---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user17
spec:
  project: workshops
  source:
    path: manifests/overlays/test
    repoURL: https://github.com/marekhanus/elyra-aidevsecops-tutorial.git
    targetRevision: HEAD
  destination:
    namespace: workshop-user17
    name: ml-prague-workshop
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
